name: homebrew

on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  wine-devel:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          brew install \
            bison \
            ccache \
            mingw-w64 \
            pkgconfig

      - name: Install runtime dependencies
        run: |
          brew install --cask gstreamer-development xquartz

      - name: Add bison to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH

      - name: Fetch wine source
        run: git clone --depth=1 https://github.com/wine-mirror/wine.git

      - name: Configure wine
        env:
          CC: "ccache clang -arch x86_64"
          CXX: "ccache clang++ -arch x86_64"
          i386_CC: "ccache i686-w64-mingw32-gcc"
          x86_64_CC: "ccache x86_64-w64-mingw32-gcc"
          GSTREAMER_LIBS: "-L/Library/Frameworks/GStreamer.framework/Libraries/ -lgstvideo-1.0 -lgstaudio-1.0 -lgstbase-1.0 -lgsttag-1.0 -lgstreamer-1.0 -Wl,-rpath,/Library/Frameworks/GStreamer.framework/Libraries -lgobject-2.0 -lglib-2.0 -lintl"
          GSTREAMER_CFLAGS: "-I/Library/Frameworks/GStreamer.framework/Headers"
          LDFLAGS: "-Wl,-headerpad_max_install_names -Wl,-rpath,/usr/X11/lib"
          PKG_CONFIG_DIR:
          PKG_CONFIG_LIBDIR: "/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig"
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure \
            --build=x86_64-apple-darwin \
            --enable-archs=i386,x86_64 \
            --enable-win64 \
            --without-alsa \
            --without-capi \
            --without-dbus \
            --without-oss \
            --without-pulse \
            --without-udev \
            --without-v4l2 \
            --without-wayland \
            --without-x

      - name: Build wine
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
