name: macports

on:
  push:
    paths-ignore:
    - '.github/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CC: ccache clang -arch x86_64
  CXX: ccache clang++ -arch x86_64
  i386_CC: ccache i686-w64-mingw32-gcc
  x86_64_CC: ccache x86_64-w64-mingw32-gcc
  CPATH: /opt/local/include
  LIBRARY_PATH: /opt/local/lib
  CFLAGS: -g -O2
  # gcc14.1 now sets -Werror-incompatible-pointer-types
  CROSSCFLAGS: -g -O2 -Wno-error=incompatible-pointer-types
  LDFLAGS: -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/../../ -Wl,-rpath,/opt/local/lib -Wl,-rpath,/opt/X11/lib
  MACOSX_DEPLOYMENT_TARGET: 10.15
  GSTREAMER_CFLAGS: -I/Library/Frameworks/GStreamer.framework/Headers
  GSTREAMER_LIBS: -L/Library/Frameworks/GStreamer.framework/Libraries/ -lgstvideo-1.0 -lgstaudio-1.0 -lgstbase-1.0 -lgsttag-1.0 -lgstreamer-1.0 -Wl,-rpath,/Library/Frameworks/GStreamer.framework/Libraries -lgobject-2.0 -lglib-2.0 -lintl

jobs:
  wine-devel:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GStreamer.framework & XQuartz
        run: |
          brew install --cask gstreamer-development xquartz

      - name: Install MacPorts
        run: . $GITHUB_WORKSPACE/.github/workflows/bootstrap_macports.sh

      - name: Add MacPorts to PATH
        run: |
          set -eu
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

      - name: Install build dependencies
        run: |
          sudo port install \
            bison \
            ccache \
            mingw-w64 \
            pkgconfig

      - name: Install runtime dependencies
        run: |
          sudo port install \
            freetype \
            gnutls-devel \
            libinotify \
            libsdl2 \
            moltenvk

      - name: Fetch wine source
        run: git clone --depth=1 https://github.com/wine-mirror/wine.git

      - name: Configure wine
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure \
            --build=x86_64-apple-darwin \
            --enable-archs=i386,x86_64 \
            --without-alsa \
            --without-capi \
            --without-dbus \
            --without-oss \
            --without-pulse \
            --without-udev \
            --without-v4l2 \
            --without-wayland \
            --without-x

      - name: Build wine
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)

  wine-staging:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MacPorts
        run: . $GITHUB_WORKSPACE/.github/workflows/bootstrap_macports.sh

      - name: Determine list of changed ports
        run: |
          set -eu
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

      - name: Install build dependencies
        run: |
          sudo port install \
            autoconf \
            bison \
            ccache \
            mingw-w64 \
            pkgconfig

      - name: Install runtime dependencies
        run: |
          sudo port install \
            freetype \
            gnutls-devel \
            libinotify \
            libsdl2 \
            moltenvk

      - name: Fetch wine-staging source
        run: git clone --depth=1 https://github.com/wine-staging/wine-staging

      - name: Grab winesource from staging
        run: |
          mkdir $GITHUB_WORKSPACE/wine
          cd wine
          git init
          git fetch https://github.com/wine-mirror/wine.git $($GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh --upstream-commit) --depth=1
          git checkout $($GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh --upstream-commit)

      - name: Apply Staging patches
        run: |
          $GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh DESTDIR=$GITHUB_WORKSPACE/wine

      - name: Configure wine
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure \
            --enable-win64 \
            --without-alsa \
            --without-capi \
            --without-dbus \
            --without-inotify \
            --without-oss \
            --without-pulse \
            --without-udev \
            --without-v4l2 \
            --without-x

      - name: Build wine
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
